export type Cell = string | number | boolean | null;
export type ClarificationTurn = { question: string; answer: string };
export type Metric = {
  id: string;
  name: string;
  description: string;
  calculation: string;
  source_tables: string[];
  date_field: string;
  included_statuses: string[];
  excluded_statuses: string[];
  currency: string | null;
  aliases: string[];
};
export type QueryPlan = {
  status: "ready" | "needs_clarification" | "blocked";
  sql: string | null;
  interpretation: string;
  metric: string | null;
  dimensions: string[];
  filters: string[];
  date_range: string;
  assumptions: string[];
  source_tables: string[];
  explanation: string;
  clarification_question: string | null;
};
export type ResultAnalysis = {
  answer: string;
  findings: string[];
  trends: string[];
  anomalies: string[];
  caveats: string[];
  follow_up_questions: string[];
};
export type QueryResponse = {
  id: number | null;
  request_id: string;
  question: string;
  dataset: "retail";
  clarification: ClarificationTurn[];
  status: "success" | "needs_clarification" | "blocked" | "failed";
  plan: QueryPlan | null;
  metric_definition: Metric | null;
  generated_sql: string;
  columns: string[];
  rows: Cell[][];
  row_count: number;
  possibly_truncated: boolean;
  analysis: ResultAnalysis | null;
  warnings: string[];
  timings: {
    generation_ms: number;
    execution_ms: number;
    analysis_ms: number;
    total_ms: number;
  };
  error: { code: string; message: string } | null;
  created_at: string;
};
export type HistoryItem = {
  id: number;
  question: string;
  dataset: "retail";
  status: string;
  row_count: number | null;
  created_at: string;
};
export type ExampleItem = { id: number; question: string };
export type Health = { status: "ok" | "degraded"; provider: string };
export type RetailOverview = {
  available: boolean;
  source: string;
  currency: "GBP";
  start: string | null;
  end: string | null;
  source_lines: number;
  sale_lines: number;
  excluded_lines: number;
  sales_invoices: number;
  gross_sales: number;
  units: number;
  months: { month: string; gross_sales: number; units: number }[];
  products: { name: string; gross_sales: number; units: number }[];
  countries: { name: string; gross_sales: number; units: number }[];
  imported_at: string | null;
  source_sha256: string | null;
  dropped_lines: number;
};
export type MarketForecast = {
  available: boolean;
  geo_code: "DE";
  geography: "Germany";
  indicator: string;
  unit: string;
  source: string;
  source_updated_at: string | null;
  source_sha256: string | null;
  observation_count: number;
  missing_periods: number;
  target_period: string | null;
  training_cutoff: string | null;
  predicted_index: number | null;
  prediction_lower: number | null;
  prediction_upper: number | null;
  baseline_index: number | null;
  method: "gradient_boosting" | "last_value" | "three_month_average" | "year_ago" | null;
  baseline_method: "last_value" | "three_month_average" | "year_ago" | null;
  ml_validation_mae: number | null;
  baseline_validation_mae: number | null;
  test_mae: number | null;
  baseline_test_mae: number | null;
  test_wape: number | null;
  test_bias: number | null;
  interval_coverage: number | null;
  confidence: "supported" | "limited" | "insufficient" | null;
  validation_months: number | null;
  test_months: number | null;
  latest_observation_status: string | null;
  history: { period: string; actual: number | null; predicted: number | null }[];
  backtest: { period: string; actual: number | null; predicted: number | null }[];
  trained_at: string | null;
};
