import type { MarketForecast, QueryResponse } from "../types/query";

export const marketForecast: MarketForecast = {
  available: true, geo_code: "DE", geography: "Germany",
  indicator: "Seasonally and calendar adjusted retail trade volume index",
  unit: "Index, 2021=100", source: "Eurostat · sts_trtu_m",
  source_updated_at: "2026-10-06T09:00:00Z", source_sha256: "1234567890abcdef",
  observation_count: 392, missing_periods: 36, target_period: "2026-09-01", training_cutoff: "2026-08-01",
  predicted_index: 113.2, prediction_lower: 110.1, prediction_upper: 116.3,
  baseline_index: 112, method: "gradient_boosting", baseline_method: "last_value",
  ml_validation_mae: 1.8, baseline_validation_mae: 2.1, test_mae: 2.2,
  baseline_test_mae: 2.6, test_wape: 0.021, test_bias: -0.4,
  interval_coverage: 0.79, confidence: "supported", validation_months: 24,
  test_months: 24, latest_observation_status: "p", trained_at: "2026-10-08T10:00:00Z",
  history: Array.from({ length: 13 }, (_, index) => ({
    period: new Date(Date.UTC(2025, 7 + index, 1)).toISOString().slice(0, 10),
    actual: 100 + index,
    predicted: null,
  })),
  backtest: [{ period: "2026-08-01", actual: 112, predicted: 111.4 }],
};
export const result: QueryResponse = {
  id: 1,
  request_id: "test-request",
  question: "Gross sales?",
  dataset: "retail",
  clarification: [],
  status: "success",
  plan: {
    status: "ready",
    sql: "SELECT SUM(quantity * unit_price) AS gross_sales FROM retail_lines WHERE is_sale",
    interpretation: "Gross sales",
    metric: "retail_gross_sales",
    dimensions: [],
    filters: [],
    date_range: "All available dates",
    assumptions: ["Use sale invoice lines"],
    source_tables: ["retail_lines"],
    explanation: "Sum sale-line value",
    clarification_question: null,
  },
  metric_definition: {
    id: "retail_gross_sales",
    name: "Gross sales",
    description: "Sale-line value",
    calculation: "SUM(quantity * unit_price) on sale lines",
    source_tables: ["retail_lines"],
    date_field: "retail_lines.invoice_date",
    included_statuses: ["sale"],
    excluded_statuses: ["cancellation", "non-sale"],
    currency: "GBP",
    aliases: [],
  },
  generated_sql: "SELECT SUM(quantity * unit_price) AS gross_sales FROM retail_lines WHERE is_sale",
  columns: ["gross_sales"],
  rows: [["123.45"]],
  row_count: 1,
  possibly_truncated: false,
  analysis: {
    answer: "Gross sales across all available dates is GBP 123.45.",
    findings: [],
    trends: [],
    anomalies: [],
    caveats: ["This is one aggregate value."],
    follow_up_questions: ["Gross sales by month?"],
  },
  warnings: [],
  timings: { generation_ms: 100, execution_ms: 5, analysis_ms: 0, total_ms: 105 },
  error: null,
  created_at: "2026-01-01T00:00:00Z",
};
export const clarification: QueryResponse = {
  ...result,
  id: 2,
  status: "needs_clarification",
  generated_sql: "",
  rows: [],
  columns: [],
  row_count: 0,
  analysis: null,
  plan: { ...result.plan!, status: "needs_clarification", sql: null,
    clarification_question: "Gross sales or invoice count?" },
};
