import type { QueryResponse } from "../types/query";
export const result: QueryResponse = {
  id: 1,
  request_id: "test-request",
  question: "Revenue?",
  clarification: [],
  status: "success",
  plan: {
    status: "ready",
    sql: "SELECT SUM(total_amount) AS revenue FROM orders WHERE status='completed'",
    interpretation: "Completed revenue",
    metric: "revenue",
    dimensions: [],
    filters: ["completed"],
    date_range: "All available dates",
    assumptions: ["EUR"],
    source_tables: ["orders"],
    explanation: "Sum completed totals",
    clarification_question: null,
  },
  metric_definition: {
    id: "revenue",
    name: "Revenue",
    description: "Completed sales",
    calculation: "SUM on completed orders",
    source_tables: ["orders"],
    date_field: "orders.order_date",
    included_statuses: ["completed"],
    excluded_statuses: ["pending", "cancelled"],
    currency: "EUR",
    aliases: [],
  },
  generated_sql:
    "SELECT SUM(total_amount) AS revenue FROM orders WHERE status='completed'",
  columns: ["revenue"],
  rows: [["123.45"]],
  row_count: 1,
  possibly_truncated: false,
  analysis: {
    answer: "Completed revenue is EUR 123.45.",
    findings: ["One completed total."],
    trends: [],
    anomalies: [],
    caveats: [],
    follow_up_questions: ["Revenue by month?"],
  },
  warnings: [],
  timings: {
    generation_ms: 100,
    execution_ms: 5,
    analysis_ms: 100,
    total_ms: 205,
  },
  error: null,
  created_at: "2026-01-01T00:00:00Z",
};
export const clarification: QueryResponse = {
  ...result,
  id: 2,
  status: "needs_clarification",
  generated_sql: "",
  rows: [],
  columns: [],
  row_count: 0,
  analysis: null,
  plan: {
    ...result.plan!,
    status: "needs_clarification",
    sql: null,
    clarification_question: "Revenue or order count?",
  },
};
