import type { QueryResponse } from "../types/query";
export const result: QueryResponse = {
  id: 1,
  request_id: "test-request",
  question: "Gross sales?",
  dataset: "retail",
  clarification: [],
  status: "success",
  plan: {
    status: "ready",
    sql: "SELECT SUM(quantity * unit_price) AS gross_sales FROM retail_lines WHERE is_sale",
    interpretation: "Gross sales",
    metric: "retail_gross_sales",
    dimensions: [],
    filters: [],
    date_range: "All available dates",
    assumptions: ["Use sale invoice lines"],
    source_tables: ["retail_lines"],
    explanation: "Sum sale-line value",
    clarification_question: null,
  },
  metric_definition: {
    id: "retail_gross_sales",
    name: "Gross sales",
    description: "Sale-line value",
    calculation: "SUM(quantity * unit_price) on sale lines",
    source_tables: ["retail_lines"],
    date_field: "retail_lines.invoice_date",
    included_statuses: ["sale"],
    excluded_statuses: ["cancellation", "non-sale"],
    currency: "GBP",
    aliases: [],
  },
  generated_sql: "SELECT SUM(quantity * unit_price) AS gross_sales FROM retail_lines WHERE is_sale",
  columns: ["gross_sales"],
  rows: [["123.45"]],
  row_count: 1,
  possibly_truncated: false,
  analysis: {
    answer: "Gross sales across all available dates is GBP 123.45.",
    findings: [],
    trends: [],
    anomalies: [],
    caveats: ["This is one aggregate value."],
    follow_up_questions: ["Gross sales by month?"],
  },
  warnings: [],
  timings: { generation_ms: 100, execution_ms: 5, analysis_ms: 0, total_ms: 105 },
  error: null,
  created_at: "2026-01-01T00:00:00Z",
};
export const clarification: QueryResponse = {
  ...result,
  id: 2,
  status: "needs_clarification",
  generated_sql: "",
  rows: [],
  columns: [],
  row_count: 0,
  analysis: null,
  plan: { ...result.plan!, status: "needs_clarification", sql: null,
    clarification_question: "Gross sales or invoice count?" },
};
